format = """
[â•­â”€](bg:#3B4252 fg:#ECEFF4)\
$python\
$username\
[î‚°](bg:#434C5E fg:#3B4252)\
$directory\
[î‚°](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[î‚°](fg:#4C566A bg:#86BBD8)\
$c\
$golang\
$java\
$rust\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#5E81AC)\
[î‚°](fg:#5E81AC bg:#33658A)\
$time\
[î‚´](fg:#33658A)
[â•°â”€â®](bg:#3B4252 fg:#ECEFF4)\
$character\
$status\
$package
"""

command_timeout = 1200

[username]
show_always = true
style_user = "bg:#3B4252 fg:#ECEFF4"
style_root = "bg:#3B4252 fg:#BF616A"
format = "[$user ]($style)"

[character]
error_symbol = " [Ã—](bold red)"
success_symbol = " [Î»](green bold)"

[status]
disabled = false
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
pipestatus = true
symbol = "â—"

[directory]
style = "bg:#434C5E"
read_only = "ï€£"
read_only_style = "bg:#434C5E fg:#BF616A bold"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "â€¦/"
format = "[ in $path ]($style)[$read_only]($read_only_style)"


[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[time]
disabled = false
time_format = "ğŸ•™ %I:%M %p"
style = "bg:#33658A"
format = "[ $time ]($style)"

[git_branch]
symbol = "ï„“ "
style = "bg:#3B4252"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#3B4252"
format = "[$all_status$ahead_behind ]($style)"
conflicted = "îœ§"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
untracked = "?"
stashed = "î­‹"
modified = "!"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

[c]
symbol = "î˜ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = "ó°Ÿ“ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨ "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "îˆµ"
style = "bg:#3B4252"
format = "[ $symbol$version (\\($virtualenv\\)) ]($style) "

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = "[ $symbol$context ]($style) "

[package]
symbol = "ï£– "
